CREATE TABLE IF NOT EXISTS spans_v2 (
    project_id VARCHAR NOT NULL,
    trace_id VARCHAR NOT NULL DEFAULT '',
    span_id VARCHAR NOT NULL DEFAULT '',
    parent_span_id VARCHAR NOT NULL DEFAULT '',
    name VARCHAR NOT NULL DEFAULT '',
    span_kind BIGINT NOT NULL DEFAULT 0,
    status_code BIGINT NOT NULL DEFAULT 0,
    status_message VARCHAR NOT NULL DEFAULT '',
    service_name VARCHAR NOT NULL DEFAULT '',
    scope_name VARCHAR NOT NULL DEFAULT '',
    scope_version VARCHAR NOT NULL DEFAULT '',
    start_time_unix_nano UBIGINT NOT NULL DEFAULT 0,
    end_time_unix_nano UBIGINT NOT NULL DEFAULT 0,
    duration BIGINT NOT NULL DEFAULT 0,
    recorded_at TIMESTAMP NOT NULL,
    trace_state VARCHAR NOT NULL DEFAULT '',
    flags BIGINT NOT NULL DEFAULT 0,
    dropped_attributes_count BIGINT NOT NULL DEFAULT 0,
    dropped_events_count BIGINT NOT NULL DEFAULT 0,
    dropped_links_count BIGINT NOT NULL DEFAULT 0,
    resource_schema_url VARCHAR NOT NULL DEFAULT '',
    scope_schema_url VARCHAR NOT NULL DEFAULT '',
    span_attributes VARCHAR NOT NULL DEFAULT '{}',
    resource VARCHAR NOT NULL DEFAULT '{}',
    scope VARCHAR NOT NULL DEFAULT '{}',
    events VARCHAR NOT NULL DEFAULT '[]',
    links VARCHAR NOT NULL DEFAULT '[]',
    otlp BLOB,
    trace_key VARCHAR NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS endpoints_v2 (
    id VARCHAR NOT NULL,
    project_id VARCHAR NOT NULL,
    trace_id VARCHAR NOT NULL DEFAULT '',
    span_id VARCHAR NOT NULL DEFAULT '',
    parent_span_id VARCHAR NOT NULL DEFAULT '',
    linked_trace_id VARCHAR NOT NULL DEFAULT '',
    endpoint VARCHAR NOT NULL DEFAULT '',
    duration BIGINT NOT NULL DEFAULT 0,
    recorded_at TIMESTAMP NOT NULL,
    status_code BIGINT NOT NULL DEFAULT 0,
    body_size BIGINT NOT NULL DEFAULT 0,
    client_ip VARCHAR NOT NULL DEFAULT '',
    attributes VARCHAR NOT NULL DEFAULT '{}',
    app_version VARCHAR NOT NULL DEFAULT '',
    server_name VARCHAR NOT NULL DEFAULT '',
    is_stream BIGINT NOT NULL DEFAULT 0,
    is_root BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS tasks_v2 (
    id VARCHAR NOT NULL,
    project_id VARCHAR NOT NULL,
    trace_id VARCHAR NOT NULL DEFAULT '',
    span_id VARCHAR NOT NULL DEFAULT '',
    parent_span_id VARCHAR NOT NULL DEFAULT '',
    linked_trace_id VARCHAR NOT NULL DEFAULT '',
    task_name VARCHAR NOT NULL DEFAULT '',
    duration BIGINT NOT NULL DEFAULT 0,
    recorded_at TIMESTAMP NOT NULL,
    client_ip VARCHAR NOT NULL DEFAULT '',
    attributes VARCHAR NOT NULL DEFAULT '{}',
    app_version VARCHAR NOT NULL DEFAULT '',
    server_name VARCHAR NOT NULL DEFAULT '',
    is_root BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ai_traces_v2 (
    id VARCHAR NOT NULL,
    project_id VARCHAR NOT NULL,
    trace_id VARCHAR NOT NULL DEFAULT '',
    span_id VARCHAR NOT NULL DEFAULT '',
    parent_span_id VARCHAR NOT NULL DEFAULT '',
    linked_trace_id VARCHAR NOT NULL DEFAULT '',
    recorded_at TIMESTAMP NOT NULL,
    duration BIGINT NOT NULL DEFAULT 0,
    status_code BIGINT NOT NULL DEFAULT 0,
    model VARCHAR NOT NULL DEFAULT '',
    response_model VARCHAR NOT NULL DEFAULT '',
    provider VARCHAR NOT NULL DEFAULT '',
    operation VARCHAR NOT NULL DEFAULT '',
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    total_tokens BIGINT NOT NULL DEFAULT 0,
    cached_tokens BIGINT NOT NULL DEFAULT 0,
    reasoning_tokens BIGINT NOT NULL DEFAULT 0,
    input_cost DOUBLE NOT NULL DEFAULT 0,
    output_cost DOUBLE NOT NULL DEFAULT 0,
    total_cost DOUBLE NOT NULL DEFAULT 0,
    trace_name VARCHAR NOT NULL DEFAULT '',
    user_id VARCHAR NOT NULL DEFAULT '',
    finish_reason VARCHAR NOT NULL DEFAULT '',
    server_name VARCHAR NOT NULL DEFAULT '',
    app_version VARCHAR NOT NULL DEFAULT '',
    storage_key VARCHAR NOT NULL DEFAULT '',
    attributes VARCHAR NOT NULL DEFAULT '{}',
    is_root BIGINT NOT NULL DEFAULT 1,
    conversation_id VARCHAR NOT NULL DEFAULT '',
    tool_call_count BIGINT NOT NULL DEFAULT 0,
    tool_names VARCHAR NOT NULL DEFAULT '',
    flagged BIGINT NOT NULL DEFAULT 0,
    flagged_terms VARCHAR NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS exceptions_v2 (
    id VARCHAR NOT NULL,
    project_id VARCHAR NOT NULL,
    trace_id VARCHAR NOT NULL DEFAULT '',
    span_id VARCHAR NOT NULL DEFAULT '',
    trace_type VARCHAR NOT NULL DEFAULT '',
    exception_hash VARCHAR NOT NULL DEFAULT '',
    stack_trace VARCHAR NOT NULL DEFAULT '',
    recorded_at TIMESTAMP NOT NULL,
    attributes VARCHAR NOT NULL DEFAULT '{}',
    app_version VARCHAR NOT NULL DEFAULT '',
    server_name VARCHAR NOT NULL DEFAULT '',
    is_message BIGINT NOT NULL DEFAULT 0,
    linked_trace_id VARCHAR NOT NULL DEFAULT '',
    session_id VARCHAR
);

CREATE INDEX IF NOT EXISTS idx_spans_v2_trace_key ON spans_v2(trace_key);
