CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    token VARCHAR(64) NOT NULL,
    framework VARCHAR(50) NOT NULL DEFAULT 'custom',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
)
