CREATE TABLE IF NOT EXISTS pages (
    id SERIAL PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    policy_id INT REFERENCES escalation_policies(id) ON DELETE SET NULL,
    policy_snapshot JSONB NOT NULL DEFAULT '{}',
    rule_id INT,
    rule_name VARCHAR(200) NOT NULL DEFAULT '',
    rule_type VARCHAR(50) NOT NULL DEFAULT '',
    subject TEXT NOT NULL DEFAULT '',
    body TEXT NOT NULL DEFAULT '',
    url TEXT NOT NULL DEFAULT '',
    severity VARCHAR(20) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    dedup_key VARCHAR(300) NOT NULL DEFAULT '',
    event_count INT NOT NULL DEFAULT 1,
    last_event_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    escalation_level INT NOT NULL DEFAULT -1,
    repeat_iteration INT NOT NULL DEFAULT 0,
    next_escalation_at TIMESTAMPTZ,
    last_escalated_at TIMESTAMPTZ,
    acknowledged_by INT,
    acknowledged_at TIMESTAMPTZ,
    resolved_by INT,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
