CREATE TABLE IF NOT EXISTS agent_attempts (
    id UUID PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    repository_id INT REFERENCES repositories(id) ON DELETE SET NULL,
    profile_id INT REFERENCES agent_profiles(id) ON DELETE SET NULL,
    number INT NOT NULL,
    kind VARCHAR(20) NOT NULL DEFAULT 'fix',
    subject_kind VARCHAR(50) NOT NULL,
    subject_ref VARCHAR(500) NOT NULL,
    executor VARCHAR(50) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'queued',
    resume BOOLEAN NOT NULL DEFAULT false,
    base_branch VARCHAR(200) NOT NULL DEFAULT '',
    fix_branch VARCHAR(200) NOT NULL DEFAULT '',
    agent VARCHAR(50) NOT NULL DEFAULT '',
    model VARCHAR(200) NOT NULL DEFAULT '',
    cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    turns INT NOT NULL DEFAULT 0,
    claimed_by VARCHAR(200) NOT NULL DEFAULT '',
    lease_expires_at TIMESTAMPTZ,
    requested_by INT,
    approved_by INT,
    error TEXT NOT NULL DEFAULT '',
    report_key VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
